### ISSUE TITLE
Archived photo's in album are not being showed.

### ISSUE THREAD

**Issue by Twan-Hoogveld** [damongolding/immich-kiosk#71] opened 2024-09-06 09:46 UTC
**Describe the bug**

Archived photo's in album are not being showed.
Most of the time I put images in the album and archive them after.
They stay visible in the immich frontend this way, but only in the folder.

The kiosk does not show archived files in the selected folder.

**To Reproduce**

1. Make album in immich
2. Add single picture
3. Archive picture
4. Load kiosk

**Expected behavior**

To see al the pictures in the album.

**Screenshots**

**Your Kiosk version**
This can be found on the startup banner in the terminal. Or in the browser via the `<meta name="version" content={ KioskVersion } />` tag or browser console.

0.8.0

**Your Kiosk installation**
- Docker (unRaid)

**Comment by damongolding** [comment] 2024-09-06 10:52
Not showing archived images is by design. I can add a config option to allow them if you think it’s something you would like?

**Comment by Twan-Hoogveld** [comment] 2024-09-06 11:43
That would be a wonderful solution!

**Comment by damongolding** [comment] 2024-09-10 11:39
@Twan-Hoogveld Would you be open to testing out a fix for this using the development docker image? 

If so,  you can use `damongolding/immich-kiosk-development:0.8.1` as your `image` in your compose file.

If you are able could you report any issues or fixes to this issue please 🙏

**Comment by Twan-Hoogveld** [comment] 2024-09-10 11:51
Of course mate.

Can confirm that the images are now being shown when the env var is set to true.
Thanks for the update!

**Closed** 2024-09-10 11:51 UTC
Labels: enhancement
